server.port=8083
spring.application.name=whitelist

# DataSource - Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=whitelist_user
spring.datasource.password=whitelist_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Flyway
spring.flyway.enabled=false

# Feign
services.producto.url=http://localhost:8081
services.user.url=http://localhost:8082