CREATE TABLE white_list (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT uq_whitelist_user_product UNIQUE (user_id, product_id)
);